/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ComputerNetworks_client;

import javax.swing.JOptionPane;

/**
 *
 * @author Ibraheem
 */
public class HomeScreen extends javax.swing.JPanel {

    String player;
    /**
     * Creates new form HomeScreen
     */
    public HomeScreen(String sPlayer) {
        initComponents();
        player=sPlayer;
        WelcomePlayer.setText("Welcome:"+player);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomePlayer = new javax.swing.JLabel();
        PlayGame = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        HighscoreText = new javax.swing.JLabel();

        WelcomePlayer.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        WelcomePlayer.setForeground(new java.awt.Color(25, 155, 100));
        WelcomePlayer.setText("Welcome ");

        PlayGame.setBackground(new java.awt.Color(0, 225, 255));
        PlayGame.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PlayGame.setText("Let's Play!");
        PlayGame.setToolTipText("");
        PlayGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayGameActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 225, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("About Game");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        HighscoreText.setText("Highscore:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlayGame, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(WelcomePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(323, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HighscoreText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(HighscoreText, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WelcomePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(PlayGame)
                .addGap(84, 84, 84)
                .addComponent(jButton2)
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PlayGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayGameActionPerformed
   flag=1;
    ;// TODO add your handling code here:
    }//GEN-LAST:event_PlayGameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    JOptionPane.showMessageDialog(this, "Developed by Ibraheem Nofal and Kamal Al Ja'bari for Computer Networks");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HighscoreText;
    private javax.swing.JButton PlayGame;
    private javax.swing.JLabel WelcomePlayer;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
    public int flag=0;
    
    public void setPlayer(String s){
    player=s;
    WelcomePlayer.setText("Welcome:"+player);

    }
    
    public void setHighscore(int score){
    HighscoreText.setText("Highscore:"+score);
    }
}
