/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ComputerNetworks_client;

import java.awt.event.WindowEvent;

/**
 *
 * @author Ibraheem
 */
public class PlayForm extends javax.swing.JPanel {

    String difficulty;
    int QuestionCount=0;
    /**
     * Creates new form PlayForm
     */
    public PlayForm(String sDifficulty) {
        ComputerNetworks_client client = new ComputerNetworks_client();
        initComponents();
        difficulty=sDifficulty;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        QuestionLabel = new javax.swing.JLabel();
        Option3RadioButton = new javax.swing.JRadioButton();
        Option1RadioButton = new javax.swing.JRadioButton();
        Option4RadioButton = new javax.swing.JRadioButton();
        Option2RadioButton = new javax.swing.JRadioButton();
        SubmitAnswerButton = new javax.swing.JButton();
        ScoreText = new javax.swing.JLabel();

        QuestionLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QuestionLabel.setText("Question 1");

        buttonGroup1.add(Option3RadioButton);
        Option3RadioButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Option3RadioButton.setText("Option1");
        Option3RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option3RadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(Option1RadioButton);
        Option1RadioButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Option1RadioButton.setText("Option1");
        Option1RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option1RadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(Option4RadioButton);
        Option4RadioButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Option4RadioButton.setText("Option1");
        Option4RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option4RadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(Option2RadioButton);
        Option2RadioButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Option2RadioButton.setText("Option1");
        Option2RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option2RadioButtonActionPerformed(evt);
            }
        });

        SubmitAnswerButton.setBackground(new java.awt.Color(0, 225, 255));
        SubmitAnswerButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SubmitAnswerButton.setText("Submit Answer");
        SubmitAnswerButton.setToolTipText("");
        SubmitAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitAnswerButtonActionPerformed(evt);
            }
        });

        ScoreText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ScoreText.setText("Score:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(QuestionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Option1RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Option4RadioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addComponent(Option3RadioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Option2RadioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(SubmitAnswerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ScoreText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScoreText)
                .addGap(3, 3, 3)
                .addComponent(QuestionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(Option1RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(Option2RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Option3RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(Option4RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(SubmitAnswerButton)
                .addGap(102, 102, 102))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Option1RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option1RadioButtonActionPerformed
    flag=1;        // TODO add your handling code here:
    }//GEN-LAST:event_Option1RadioButtonActionPerformed

    private void Option2RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option2RadioButtonActionPerformed
    flag=2;        // TODO add your handling code here:
    }//GEN-LAST:event_Option2RadioButtonActionPerformed

    private void Option3RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option3RadioButtonActionPerformed
    flag=3;        // TODO add your handling code here:
    }//GEN-LAST:event_Option3RadioButtonActionPerformed

    private void Option4RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option4RadioButtonActionPerformed
    flag=4;        // TODO add your handling code here:
    }//GEN-LAST:event_Option4RadioButtonActionPerformed

    private void SubmitAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitAnswerButtonActionPerformed
    QuestionCount++;
    if(QuestionCount==4){
   this.getParent().setVisible(false);
    }
        answered=true;        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitAnswerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Option1RadioButton;
    private javax.swing.JRadioButton Option2RadioButton;
    private javax.swing.JRadioButton Option3RadioButton;
    private javax.swing.JRadioButton Option4RadioButton;
    private javax.swing.JLabel QuestionLabel;
    private javax.swing.JLabel ScoreText;
    private javax.swing.JButton SubmitAnswerButton;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
    public int flag=0;
    public int QuestionNumber=1;
    public boolean answered=false;
    public void setOption1(String text){
    Option1RadioButton.setText(text);
    
    }
    
    public void setOption2(String text){
    Option2RadioButton.setText(text);
    }
    
    public void setOption3(String text){
    Option3RadioButton.setText(text);
    }
    
    public void setOption4(String text){
    Option4RadioButton.setText(text);
    }
    
     public void setQuestion(String text){
    QuestionLabel.setText(text);
    }
     
     public void setScore(int score){
     ScoreText.setText("Score:"+score);
     
     }
}
